spring:
  application:
    name: kintai
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 10m

logging:
  level:
    com.kintai: DEBUG
    org.springframework.web: DEBUG
