spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kintai?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: your_mysql_password_here
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    com.kintai: INFO
    org.springframework.web: INFO

# PDFサービス設定
pdf:
  service:
    url: http://localhost:8081
    api-key: test-key
    require-auth: false
