spring:
  application:
    name: kintai
  profiles:
    active: dev  # デフォルトはdevプロファイル
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true

---
# devプロファイル設定
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true

---
# prodプロファイル設定
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  flyway:
    enabled: true
    url: ${DATABASE_URL}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 10m

logging:
  level:
    com.kintai: DEBUG
    org.springframework.web: DEBUG

# PDFサービス設定
pdf:
  service:
    url: ${PDF_SERVICE_URL:http://localhost:8081}
    api-key: ${PDF_SERVICE_API_KEY:test-key}
    require-auth: ${PDF_SERVICE_REQUIRE_AUTH:false}
